khaleesi/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.core.urlresolvers import reverse
from django.views.generic.base import RedirectView
from django.contrib.admin import site
from django.contrib import admin
#from tastypie.api import Api
from track.views import *
from api import *

#admin.autodiscover()

#v1_api = Api(api_name='v1')
#v1_api.register(IssueResource())
#v1_api.register(TareaResource())
#v1_api.register(PizarronResource())
#v1_api.register(UserResource())

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/admin')),
    #url(r'^api/', include(v1_api.urls)),
    url(r'^admin/resume/$', site.admin_view(resume)),
    url(r'^admin/gantt/$', site.admin_view(gantt_all)),
    url(r'^admin/view/(?P<intoken>[a-f0-9]+)/(?P<v>\w+)/$', view_xml),
    url(r'^admin/json/board/$', site.admin_view(json_board)),
    url(r'^admin/auth/profile/$', site.admin_view(user_profile), name='user_profile'),
    url(r'^admin/track/proyecto/(?P<proyecto_id>\d+)/gantt/$', site.admin_view(gantt_por_proyecto)),
    url(r'^admin/track/user/(?P<user_id>\d+)/gantt/$', site.admin_view(gantt_por_usuario)),
    url(r'^admin/track/user/(?P<user_id>\d+)/proyecto/(?P<proyecto_id>\d+)/gantt/$', site.admin_view(gantt_por_usuario_proyecto)),
    url(r'^admin/track/tarea/(?P<tarea_id>\d+)/board/(?P<status_id>\d+)/$', site.admin_view(board)),
    url(r'^admin/track/tarea/(?P<tarea_id>\d+)/change/board/(?P<status_id>\d+)/$', site.admin_view(board)),
    url(r'^jet/', include('jet.urls', 'jet')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

changelog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.html import format_html
from django.core.urlresolvers import reverse

class tipo_dato(models.Model):
    dato = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)

    def __unicode__(self):
        return self.dato

class tipo_objeto(models.Model):
    tipo = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)

    def __unicode__(self):
        return self.tipo

class objeto(models.Model):
    objeto = models.CharField(max_length=100)
    tipo = models.ForeignKey(tipo_objeto)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)
    relacion_objeto = models.ForeignKey('self', blank=True, null=True, related_name="relacion")
    tipo_dato = models.ForeignKey(tipo_dato, blank=True, null=True)
    deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(User, blank=True, null=True, default=None, related_name='objeto_deleted_by')
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)

    def __unicode__(self):
        return self.objeto
    
    def created_by_link(self):
        return format_html('<a href="#?created_by__id__exact={0}">{1}</a>', self.created_by.id, self.created_by.username)
    created_by_link.short_description = 'Created by'
    created_by_link.admin_order_field = 'created_by'

    def relacion_objeto_link(self):
        if self.relacion_objeto:
            return format_html('<a href="?relacion_objeto__id__exact={0}">{1}</a>', self.relacion_objeto.id, self.relacion_objeto.objeto)
        return '--'
    relacion_objeto_link.short_description = 'Relacion Objeto'    
    relacion_objeto_link.admin_order_field = 'relacion_objeto__objeto'

    def tipo_objeto_link(self):
        return format_html('<a href="?tipo__id__exact={0}">{1}</a>', self.tipo.id, self.tipo)
    tipo_objeto_link.short_description = 'Tipo objeto'
    tipo_objeto_link.admin_order_field = 'tipo'
    
    def tipo_dato_link(self):
        if self.tipo_dato:
            return format_html('<a href="?tipo__id__exact={0}">{1}</a>', self.tipo_dato.id, self.tipo_dato)
        return '--'
    tipo_dato_link.short_description = 'Tipo dato'
    tipo_dato_link.admin_order_field = 'tipo_dato'

class tipo_cambio(models.Model):
    tipo = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)
    descripcion = models.TextField()

    def __unicode__(self):
        return self.tipo

class cambio(models.Model):
    objeto = models.ForeignKey(objeto)
    tipo = models.ForeignKey(tipo_cambio)
    nota = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,blank=True,null=True)

    def __unicode__(self):
        return '{0}: {1}'.format(self.tipo, self.objeto)

    def get_objeto_cambio(self):
        return format_html('<a href="?q={0}">{0}</a>', self.objeto.relacion_objeto)
    get_objeto_cambio.short_description = 'Cambio'
    get_objeto_cambio.admin_order_field = 'objeto__relacion_objeto'
    
    def objeto_link(self):
        return format_html('<a href="?objeto__id__exact={0}">{1}</a>', self.objeto.id, self.objeto)
    objeto_link.short_description = 'Objeto'
    objeto_link.admin_order_field = 'objeto'

    def tipo_link(self):
        return format_html('<a href="?tipo__id__exact={0}">{1}</a>', self.tipo.id, self.tipo)
    tipo_link.short_description = 'Tipo'
    tipo_link.admin_order_field = 'tipo'

    def nota_corta(self):
        nota = self.nota[0:120]
        if len(self.nota[120:]) > 0:
            nota = nota + '...'
        return nota
    nota_corta.short_description = 'Nota'
    nota_corta.admin_order_field = 'nota'

    def created_by_link(self):
        return format_html('<a href="#?created_by__id__exact={0}">{1}</a>', self.created_by.id, self.created_by.username)
    created_by_link.short_description = 'Created by'
    created_by_link.admin_order_field = 'created_by'

track/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import format_html
from django.utils.html import strip_tags
from django.utils.translation import gettext as _
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
#from tastypie.models import *
from khaleesi.sensible import *
from datetime import datetime
import ast
import random

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    is_email_active = models.BooleanField(default=True)
    token = models.CharField(max_length=50, blank=True, null=True)
    start_time = models.TimeField(null=True, blank=True)
    end_time = models.TimeField(null=True, blank=True)
    lunch_time = models.TimeField(null=True, blank=True)
    sun = models.BooleanField(default=False)
    mon = models.BooleanField(default=True)
    tue = models.BooleanField(default=True)
    wed = models.BooleanField(default=True)
    thu = models.BooleanField(default=True)
    fri = models.BooleanField(default=True)
    sat = models.BooleanField(default=False)
    show_resume = models.BooleanField(default=False)

class proyecto(models.Model):
    proyecto = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    link = models.CharField(max_length=1024, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)
    deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(User, blank=True, null=True, default=None, related_name='proyecto_deleted_by')
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    archived = models.BooleanField(default=False)

    def __unicode__(self):
        return self.proyecto

    def activos(self):
        return format_html(u'<a href="/admin/track/modulo/?q=&proyecto__proyecto={0}&deleted__exact=0">{1}</a>', self.proyecto, modulo.objects.filter(proyecto=self, deleted=False).count())

    def cancelados(self):
        return format_html(u'<a href="/admin/track/modulo/?q=&proyecto__proyecto={0}&deleted__exact=1">{1}</a>', self.proyecto, modulo.objects.filter(proyecto=self, deleted=True).count())

    def gantt_link(self):
        return format_html(u'<a href="/admin/track/proyecto/{}/gantt/">Ver</a>'.format(self.id))
    gantt_link.short_description = 'Gantt'
    gantt_link.allow_tags = True

    def link_short(self):
        return format_html(u'<a href="{}"><span class="fa fa-link"></span></a>'.format(self.link))
    link_short.short_description = 'Link'
    link_short.allow_tags = True
    link_short.admin_order_field = 'link'

class modulo(models.Model):
    proyecto = models.ForeignKey(proyecto)
    modulo = models.CharField(max_length=100)
    descripcion = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)
    deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(User, blank=True, null=True, default=None, related_name='modulo_deleted_by')
    deleted_at = models.DateTimeField(blank=True, null=True, default=None)
    archived = models.BooleanField(default=False)

    def __unicode__(self):
        return u'{0}->{1}'.format(self.proyecto, self.modulo)

    def proyecto_link(self):
        return format_html('<a href="/admin/track/proyecto/{0}/">{1}</a>', self.proyecto.id, self.proyecto)
    proyecto_link.short_description = 'Proyecto'
    proyecto_link.allow_tags = True
    proyecto_link.admin_order_field = 'proyecto'

    def issues_resueltos(self):
        return format_html(u'<a href="/admin/track/issue/?q=&modulo__modulo={0}&status__exact=1">{1}</a>', self.modulo, issue.objects.filter(modulo=self, status=1).count())
    issues_resueltos.short_description = 'Resueltos'

    def issues_abiertos(self):
        return format_html(u'<a href="/admin/track/issue/?q=&status__exact=0">{0}</a>', issue.objects.filter(modulo=self, status=0).count())
    issues_abiertos.short_description = 'Abiertos'

    def issues_abandonados(self):
        return format_html(u'<a href="/admin/track/issue/?q=&status__exact=2">{0}</a>', issue.objects.filter(modulo=self, status=2).count())
    issues_abandonados.short_description = 'Abandonados'

    def issues_cancelados(self):
        return format_html(u'<a href="/admin/track/issue/?q=&status__exact=3">{0}</a>', issue.objects.filter(modulo=self, status=3).count())
    issues_cancelados.short_description = 'Cancelados'

class tarea(models.Model):
    STATUS_CHOICES = (
        (0, 'Abierto'),
        (1, 'Cerrado')
    )
    modulo = models.ForeignKey(modulo)
    nombre = models.CharField(max_length=75)
    descripcion = models.TextField()
    fecha_inicial = models.DateTimeField(null=True)
    fecha_final = models.DateTimeField(null=True)
    horas_estimadas = models.IntegerField(blank=True, null=True, default=None)
    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    responsable = models.ForeignKey(User, related_name='tarea_responsable')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(User, blank=True, null=True)

    def get_status(self):
        return self.STATUS_CHOICES[self.status][1]

    def __unicode__(self):
        return '{}'.format(self.id)

    def get_horas_estimadas(self):
        if self.horas_estimadas:
            return self.horas_estimadas
        return 0
    get_horas_estimadas.short_description = 'Hrs Est.'

    def get_horas_reales(self):
        horas = 0
        dateini = None
        datefin = None
        last_status = None
        list_pizarron = pizarron.objects.filter(tarea=self).order_by('created_at')

        for view_pizarron in list_pizarron:
            if view_pizarron.status == 2 and last_status != 2:
                dateini = view_pizarron.created_at
            if view_pizarron.status != 2:
                datefin = view_pizarron.created_at
                if dateini and datefin:
                    horas_lambda = datefin - dateini
                    horas += horas_lambda.total_seconds()
                    dateini = None
            last_status = view_pizarron.status

        return horas/3600

    def get_last_log(self):
        try:
            return pizarron.objects.filter(tarea=self).order_by('-created_at')[:1][0]
        except:
            return None

    def get_color_status(self):
        colors = {
            0: '#8A2BE2', # purple - Asignado
            1: '#FFA500', # yellow - Pendiente
            2: '#00008B', # blue - En Proceso
            3: '#FF4500', # orange - Pausado
            4: '#006400', # green - Terminado
            5: '#8B0000', # red - Bloqueado
            6: '#8A2BE2', # purple - Reasignado
            7: '#778899', # grey - Abandonada
        }
        try:
            return colors[self.get_last_log().status]
        except:
            return colors[0]

    def get_last_status(self):
        try:
            return self.get_last_log().get_status()
        except:
            return 'Sin actividad'

    def get_last_status_number(self):
        try:
            return self.get_last_log().get_status_number()
        except:
            return -1

    def get_pizarron(self):
        html = u'<span style="color: {1};">{0}</span>'.format(self.get_last_status(), self.get_color_status())
        return format_html(html)
    get_pizarron.short_description = 'Pizarrón'

    def get_op(self):
        html = u''
        if self.get_last_status_number() in [0, 1, 3]:
            html += '<a href="/admin/track/tarea/{tarea_id}/change/board/2/?list=True" title="Comenzar Tarea" style="margin-left: 4px;"><span class="fa fa-play" aria-hidden="true" /></a>'.format(tarea_id=self.id)
        if self.get_last_status_number() in [2]:
            html += '<a href="/admin/track/tarea/{tarea_id}/change/board/3/?list=True" title="Pausar Tarea" style="margin-left: 4px;"><span class="fa fa-pause" aria-hidden="true" /></a>'.format(tarea_id=self.id)
        return format_html(html)
    get_op.short_description = 'OP'

    def proyecto_link(self):
        return self.modulo.proyecto_link()
    proyecto_link.short_description = 'Proyecto'
    proyecto_link.allow_tags = True
    proyecto_link.admin_order_field = 'proyecto'

    def modulo_link(self):
        return format_html(u'<a href="/admin/track/modulo/{0}/">{1}</a>', self.modulo.id, u'{}'.format(self.modulo.modulo))
    modulo_link.short_description = 'Modulo'
    modulo_link.allow_tags = True
    modulo_link.admin_order_field = 'modulo'

    def responsable_link(self):
        return format_html('<a href="/admin/track/user/{0}/proyecto/{1}/gantt/">{2}</a>', self.responsable.id, self.modulo.proyecto.id, self.responsable.username)
    responsable_link.short_description = 'Responsable'
    responsable_link.allow_tags = True
    responsable_link.admin_order_field = 'responsable'

    def periodo(self):
        if self.fecha_final.year == self.fecha_inicial.year:
            if self.fecha_final.month == self.fecha_inicial.month:
                # Mismo año, mismo mes
                return format_html('{} - {}, {} {}'.format(self.fecha_inicial.strftime('%d'), self.fecha_final.strftime('%d'), self.fecha_final.strftime('%B'), self.fecha_final.strftime('%Y')))
            else:
                # Mismo año, diferente mes
                return format_html('{} - {}, {}'.format(self.fecha_inicial.strftime('%d de %B'), self.fecha_final.strftime('%d de %B'), self.fecha_final.strftime('%Y')))
        else:
            # Diferente Año

track/templates/base_email.html
<style>
    *{
        margin: 0px;
        padding: 0px;
        font-family: "Helvetica", Helvetica, Arial, sans-serif;
        font-size: 14px;
    }
    .content{
        margin: auto;
        /*width: 80%;*/
        border: 1px solid #999;
    }
    a {
        color: #348eda;
    }
    .btn-primary {
        text-decoration: none;
        color: #FFF;
        background-color: #348eda;
        border: solid #348eda;
        border-width: 10px 20px;
        line-height: 2;
        font-weight: bold;
        margin-right: 10px;
        text-align: center;
        cursor: pointer;
        display: inline-block;
        border-radius: 25px;
    }

    .btn-secondary {
        text-decoration: none;
        color: #FFF;
        background-color: #aaa;
        border: solid #aaa;
        border-width: 10px 20px;
        line-height: 2;
        font-weight: bold;
        margin-right: 10px;
        text-align: center;
        cursor: pointer;
        display: inline-block;
        border-radius: 25px;
    }

    .last {
        margin-bottom: 0;
    }

    .first {
        margin-top: 0;
    }

    .padding {
        padding: 10px 0;
    }
    h1, h2, h3 {
        font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
        line-height: 1.1;
        margin-bottom: 15px;
        color: #000;
        margin: 40px 0 10px;
        line-height: 1.2;
        font-weight: 200;
    }

    h1 {
        font-size: 36px;
    }
    h2 {
        font-size: 28px;
    }
    h3 {
        font-size: 22px;
    }
    h4{
        margin-bottom: 10px;
    }

    ul, ol {
        margin-bottom: 10px;
        font-weight: normal;
        font-size: 14px;
    }

    ul li, ol li {
        margin-left: 5px;
        list-style-position: inside;
    }
    p{
        text-align: justify;
    }
    blockquote {
      background: #f9f9f9;
      border-left: 10px solid #ccc;
      margin: 1.5em 10px;
      padding: 0.5em 10px;
      quotes: "\201C""\201D""\2018""\2019";
    }
    blockquote:before {
      color: #ccc;
      content: open-quote;
      font-size: 4em;
      line-height: 0.1em;
      margin-right: 0.25em;
      vertical-align: -0.4em;
    }
    blockquote p {
      display: inline;
    }
</style>
<table width="100%" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <!-- content -->
			<div class="content">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <hr/>
                            <div style="background: #EEE; padding: 10px;">
                                <h1>{% block titulo %}{% endblock %}</h1>
                            </div>
                            <hr/>
                            <div style="padding: 10px; text-align: justify;">
                                {% block descripcion %}{% endblock %}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div style="padding: 10px; text-align: justify;">
                                {% block contenido %}{% endblock %}
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <hr/>
                            <div style="padding: 10px; text-align: justify; background: #EEE;">
                                {% block patas %}
                                <p style="text-align: center;">
                                    <a href="#">koalaideas.com</a> | <a href="https://github.com/lesthack/khaleesi">Github</a>
                                </p>
                                {% endblock %}                            
                            </div>
                        </td>
                    </tr>
                </table>
			</div>
			<!-- /content -->

        </td>
    </tr>
</table>

track/templates/base_email_nota.html
{% extends "base_email.html" %}
{% block titulo%}Nota del Issue <a href="{{ URL_HOST }}/admin/track/issue/{{ nota.issue.id }}/">{{ nota.issue.id }}</a>{% endblock %}
{% block contenido %}
    <p>Nota por el usuario <b>{{ nota.created_by.username }} [<small>{{ nota.created_at }}</small>]</b></p>
    <div class="nota" style="margin-top: 10px; margin-left: 10px;">
      <div style="display: inline-block; width: 30px;">
        {% if nota.like == '1' %}&#x1f44d;{% endif %}
      </div>
      <div style="display: inline-block;">
          {{ nota.nota|safe|linebreaks }}
      </div>
    </div>
    <p style="padding: 10px; text-align: center;">
    <a href="{{ URL_HOST }}/admin/track/issue/{{ nota.issue.id }}/" class="btn-primary">Ver Detalles</a>
    </p>
    <hr/>
{% endblock %}

track/templates/issue_new_form.html
{% extends "admin/change_form.html" %}
{% block after_field_sets %}
{% load static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<script src="{% static 'js/advanced.js' %}"></script>
<script src="{% static 'js/wysihtml5-0.3.0.min.js' %}"></script>
<style>
  .wysihtml5-command-active {
    font-weight: bold;
  }

  [data-wysihtml5-dialog] {
    margin: 5px 0 0;
    padding: 5px;
    border: 1px solid #666;
  }

  a[data-wysihtml5-command-value="red"] {
    color: red;
  }

  a[data-wysihtml5-command-value="green"] {
    color: green;
  }

  a[data-wysihtml5-command-value="blue"] {
    color: blue;
  }
</style>
<div id="toolbar_desc" style="display: none; clear: both;">
    <a data-wysihtml5-command="bold" title="CTRL+B">bold</a> |
    <a data-wysihtml5-command="italic" title="CTRL+I">italic</a> |
    <a data-wysihtml5-command="createLink">insert link</a> |
    <a data-wysihtml5-command="insertImage">insert image</a> |
    <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h1">h1</a> |
    <a data-wysihtml5-command="formatBlock" data-wysihtml5-command-value="h2">h2</a> |
    <a data-wysihtml5-command="insertUnorderedList">insertUnorderedList</a> |
    <a data-wysihtml5-command="insertOrderedList">insertOrderedList</a> |
    <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="red">red</a> |
    <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="green">green</a> |
    <a data-wysihtml5-command="foreColor" data-wysihtml5-command-value="blue">blue</a> |
    <a data-wysihtml5-command="insertSpeech">speech</a>
    <a data-wysihtml5-action="change_view">switch to html view</a>
    
    <div data-wysihtml5-dialog="createLink" style="display: none;">
      <label>
        Link:
        <input data-wysihtml5-dialog-field="href" value="http://">
      </label>
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>
    
    <div data-wysihtml5-dialog="insertImage" style="display: none;">
      <label>
        Image:
        <input data-wysihtml5-dialog-field="src" value="http://">
      </label>
      <label>
        Align:
        <select data-wysihtml5-dialog-field="className">
          <option value="">default</option>
          <option value="wysiwyg-float-left">left</option>
          <option value="wysiwyg-float-right">right</option>
        </select>
      </label>
      <a data-wysihtml5-dialog-action="save">OK</a>&nbsp;<a data-wysihtml5-dialog-action="cancel">Cancel</a>
    </div>  
</div>
<script>
  $(function(){
    $("#id_descripcion").css('width','90%').before($("#toolbar_desc"));
    var editor = new wysihtml5.Editor("id_descripcion", { 
      toolbar:      "toolbar_desc", // id of toolbar element
      stylesheets: "/static/css/stylesheet.css",
      parserRules:  wysihtml5ParserRules // defined in parser rules set 
    });
  });
</script>
{% endblock %}

track/templates/profile_form.html
{% extends "admin/base_site.html" %}
{% load i18n admin_static admin_modify admin_urls %}

{% block bodyclass %}Profile{% endblock %}

{% block content %}
<style>
    label{
        float: inherit !important;
        width: inherit !important;
        display: inline-block !important;
    }
</style>
  <div id="content-main">
    <form action="" method="post" id="profile_form" class="form-horizontal">
      {% csrf_token %}  
      <div>
        {% if form.errors %}
          <div class="alert alert-error">
              {% blocktrans count counter=form.errors.items|length %}Please correct the error below.{% plural %} Please correct the errors below.
              {% endblocktrans %}
          </div>
        {% endif %}

        <div class="alert alert-info">{% blocktrans %}Puede obtener su Token de Pushbullet <a href="https://www.pushbullet.com/account">aqui</a>.{% endblocktrans %}</div>
        
        <fieldset class="module aligned">
          <div class="control-group{{ form.token.errors|yesno:' error,' }}">
            <div class="control-label">
              <label for="id_token">{% trans 'Pushbullet Token' %}:</label>
            </div>
            <div class="controls">
              {{ form.token }}
              <div class="help-inline">{{ form.token.errors }}</div>
            </div>
          </div>

          <div class="control-group{{ form.is_mail_active.errors|yesno:' error,' }}">
            <div class="control-label">
              <label class="required">{% trans 'Recibir emails' %}:</label>
            </div>
            <div class="controls">
              <div>{{ form.is_email_active }}</div>
              <div class="help-inline">{{ form.is_email_active.errors }}</div>
            </div>
          </div>

          {% comment %}
          <div class="control-group">
            <div class="control-label">
              <label for="id_is_email_active" class="required">{% trans 'Tastypie API Key' %}:</label>
            </div>
            <div class="controls">{{ user.get_apikey }}</div>
          </div>
          {% endcomment %}

          <div class="control-group">
            <div class="control-label">
              <label for="id_start_time" class="required">{% trans 'Hora inicial' %}:</label>
            </div>
            <div class="controls">
                {{ form.start_time }}
              <div class="help-inline">{{ form.start_time.errors }}</div>
            </div>
          </div>

          <div class="control-group">
            <div class="control-label">
              <label for="id_start_time" class="required">{% trans 'Hora de comida' %}:</label>
            </div>
            <div class="controls">
                {{ form.lunch_time }}
              <div class="help-inline">{{ form.lunch_time.errors }}</div>
            </div>
          </div>

          <div class="control-group">
            <div class="control-label">
              <label for="id_end_time" class="required">{% trans 'Hora final' %}:</label>
            </div>
            <div class="controls">
                {{ form.end_time }}
              <div class="help-inline">{{ form.end_time.errors }}</div>
            </div>
          </div>

          <div class="control-group">
            <div class="control-label">
              <label for="id_dias" class="required">{% trans 'Días de Trabajo' %}:</label>
            </div>
            <div class="controls">
                <div>{{ form.sun }} {{ form.sun.label }}</div>
                <div>{{ form.mon }} {{ form.mon.label }}</div>
                <div>{{ form.tue }} {{ form.tue.label }}</div>
                <div>{{ form.wed }} {{ form.wed.label }}</div>
                <div>{{ form.thu }} {{ form.thu.label }}</div>
                <div>{{ form.fri }} {{ form.fri.label }}</div>
                <div>{{ form.sat }} {{ form.sat.label }}</div>
            </div>
          </div>

          {% if request.user.is_superuser %}
          <div class="control-group">
            <div class="control-label">
              <label for="id_resume" class="required">{% trans 'Mostrar Resumen' %}:</label>
            </div>
            <div class="controls">
                <div>{{ form.show_resume }}</div>
            </div>
          </div>
          {% endif %}

        </fieldset>

        {% if saved %}
        <br/>
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {% trans 'Done' %}. 
        </div>
        {% endif %}

        <div class="submit-row submit-row-bottom">
          <input type="submit" value="{% trans 'Save' %}" class="default btn btn-info"/>
        </div>

        <script type="text/javascript">document.getElementById("id_token").focus();</script>
      </div>
    </form>
  </div>
{% endblock %}